// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: canvas/canvas/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCanvasRequest struct {
}

func (m *QueryGetCanvasRequest) Reset()         { *m = QueryGetCanvasRequest{} }
func (m *QueryGetCanvasRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCanvasRequest) ProtoMessage()    {}
func (*QueryGetCanvasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{2}
}
func (m *QueryGetCanvasRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCanvasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCanvasRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCanvasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCanvasRequest.Merge(m, src)
}
func (m *QueryGetCanvasRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCanvasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCanvasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCanvasRequest proto.InternalMessageInfo

type QueryGetCanvasResponse struct {
	Canvas Canvas `protobuf:"bytes,1,opt,name=Canvas,proto3" json:"Canvas"`
}

func (m *QueryGetCanvasResponse) Reset()         { *m = QueryGetCanvasResponse{} }
func (m *QueryGetCanvasResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCanvasResponse) ProtoMessage()    {}
func (*QueryGetCanvasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{3}
}
func (m *QueryGetCanvasResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCanvasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCanvasResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCanvasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCanvasResponse.Merge(m, src)
}
func (m *QueryGetCanvasResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCanvasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCanvasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCanvasResponse proto.InternalMessageInfo

func (m *QueryGetCanvasResponse) GetCanvas() Canvas {
	if m != nil {
		return m.Canvas
	}
	return Canvas{}
}

type QueryGetStoredColorsRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetStoredColorsRequest) Reset()         { *m = QueryGetStoredColorsRequest{} }
func (m *QueryGetStoredColorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredColorsRequest) ProtoMessage()    {}
func (*QueryGetStoredColorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{4}
}
func (m *QueryGetStoredColorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredColorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredColorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredColorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredColorsRequest.Merge(m, src)
}
func (m *QueryGetStoredColorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredColorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredColorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredColorsRequest proto.InternalMessageInfo

func (m *QueryGetStoredColorsRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetStoredColorsResponse struct {
	StoredColors StoredColors `protobuf:"bytes,1,opt,name=storedColors,proto3" json:"storedColors"`
}

func (m *QueryGetStoredColorsResponse) Reset()         { *m = QueryGetStoredColorsResponse{} }
func (m *QueryGetStoredColorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredColorsResponse) ProtoMessage()    {}
func (*QueryGetStoredColorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{5}
}
func (m *QueryGetStoredColorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredColorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredColorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredColorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredColorsResponse.Merge(m, src)
}
func (m *QueryGetStoredColorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredColorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredColorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredColorsResponse proto.InternalMessageInfo

func (m *QueryGetStoredColorsResponse) GetStoredColors() StoredColors {
	if m != nil {
		return m.StoredColors
	}
	return StoredColors{}
}

type QueryAllStoredColorsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredColorsRequest) Reset()         { *m = QueryAllStoredColorsRequest{} }
func (m *QueryAllStoredColorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredColorsRequest) ProtoMessage()    {}
func (*QueryAllStoredColorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{6}
}
func (m *QueryAllStoredColorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredColorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredColorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredColorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredColorsRequest.Merge(m, src)
}
func (m *QueryAllStoredColorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredColorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredColorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredColorsRequest proto.InternalMessageInfo

func (m *QueryAllStoredColorsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStoredColorsResponse struct {
	StoredColors []StoredColors      `protobuf:"bytes,1,rep,name=storedColors,proto3" json:"storedColors"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredColorsResponse) Reset()         { *m = QueryAllStoredColorsResponse{} }
func (m *QueryAllStoredColorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredColorsResponse) ProtoMessage()    {}
func (*QueryAllStoredColorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f6eb60a4bb63216, []int{7}
}
func (m *QueryAllStoredColorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredColorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredColorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredColorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredColorsResponse.Merge(m, src)
}
func (m *QueryAllStoredColorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredColorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredColorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredColorsResponse proto.InternalMessageInfo

func (m *QueryAllStoredColorsResponse) GetStoredColors() []StoredColors {
	if m != nil {
		return m.StoredColors
	}
	return nil
}

func (m *QueryAllStoredColorsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "canvas.canvas.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "canvas.canvas.QueryParamsResponse")
	proto.RegisterType((*QueryGetCanvasRequest)(nil), "canvas.canvas.QueryGetCanvasRequest")
	proto.RegisterType((*QueryGetCanvasResponse)(nil), "canvas.canvas.QueryGetCanvasResponse")
	proto.RegisterType((*QueryGetStoredColorsRequest)(nil), "canvas.canvas.QueryGetStoredColorsRequest")
	proto.RegisterType((*QueryGetStoredColorsResponse)(nil), "canvas.canvas.QueryGetStoredColorsResponse")
	proto.RegisterType((*QueryAllStoredColorsRequest)(nil), "canvas.canvas.QueryAllStoredColorsRequest")
	proto.RegisterType((*QueryAllStoredColorsResponse)(nil), "canvas.canvas.QueryAllStoredColorsResponse")
}

func init() { proto.RegisterFile("canvas/canvas/query.proto", fileDescriptor_3f6eb60a4bb63216) }

var fileDescriptor_3f6eb60a4bb63216 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x86, 0xb3, 0xb5, 0x0d, 0x38, 0x56, 0x84, 0x31, 0xb1, 0xba, 0x8d, 0xab, 0x1d, 0x62, 0x95,
	0x2a, 0x3b, 0xb4, 0x79, 0x82, 0xb6, 0x68, 0x41, 0x10, 0x6a, 0xbc, 0xf3, 0x46, 0x26, 0xe9, 0xb0,
	0x04, 0xb6, 0x33, 0xdb, 0x9d, 0x69, 0x69, 0x11, 0x6f, 0x7c, 0x82, 0x82, 0x08, 0x3e, 0x85, 0xcf,
	0xd1, 0xcb, 0x82, 0x37, 0x5e, 0x89, 0x24, 0x3e, 0x88, 0x64, 0xce, 0x59, 0xba, 0x9b, 0x4e, 0x12,
	0xf1, 0x6a, 0xb3, 0x73, 0xfe, 0x73, 0xfe, 0xef, 0x6c, 0xfe, 0x5d, 0xf2, 0xa0, 0x2f, 0xd4, 0x89,
	0x30, 0x1c, 0x2f, 0x47, 0xc7, 0x32, 0x3f, 0x8b, 0xb3, 0x5c, 0x5b, 0x4d, 0x6f, 0xc3, 0x59, 0x0c,
	0x97, 0xb0, 0x91, 0xe8, 0x44, 0xbb, 0x0a, 0x1f, 0xff, 0x02, 0x51, 0xd8, 0x4a, 0xb4, 0x4e, 0x52,
	0xc9, 0x45, 0x36, 0xe0, 0x42, 0x29, 0x6d, 0x85, 0x1d, 0x68, 0x65, 0xb0, 0xba, 0xd1, 0xd7, 0xe6,
	0x50, 0x1b, 0xde, 0x13, 0x46, 0xc2, 0x6c, 0x7e, 0xb2, 0xd9, 0x93, 0x56, 0x6c, 0xf2, 0x4c, 0x24,
	0x03, 0xe5, 0xc4, 0xa8, 0x0d, 0xab, 0x24, 0x99, 0xc8, 0xc5, 0xa1, 0xf1, 0xd7, 0x10, 0x0c, 0x6a,
	0x6b, 0xd5, 0x9a, 0xb1, 0x3a, 0x97, 0x07, 0x1f, 0xfa, 0x3a, 0xd5, 0x39, 0x4a, 0x58, 0x83, 0xd0,
	0xb7, 0x63, 0xf3, 0x7d, 0x37, 0xb3, 0x2b, 0x8f, 0x8e, 0xa5, 0xb1, 0xec, 0x35, 0xb9, 0x5b, 0x39,
	0x35, 0x99, 0x56, 0x46, 0xd2, 0x0e, 0xa9, 0x83, 0xf7, 0xfd, 0xe0, 0x71, 0xf0, 0xec, 0xd6, 0x56,
	0x33, 0xae, 0x3c, 0x87, 0x18, 0xe4, 0x3b, 0x8b, 0x17, 0xbf, 0x1e, 0xd5, 0xba, 0x28, 0x65, 0x2b,
	0xa4, 0xe9, 0x66, 0xed, 0x49, 0xbb, 0xeb, 0x64, 0x85, 0xc9, 0x1b, 0x72, 0x6f, 0xb2, 0x70, 0xe5,
	0x03, 0x27, 0x53, 0x7c, 0xa0, 0x58, 0xf8, 0xc0, 0x1d, 0xeb, 0x90, 0xd5, 0x62, 0xdc, 0x3b, 0xb7,
	0xe8, 0xae, 0xdb, 0x13, 0xdd, 0x68, 0x83, 0x2c, 0x0d, 0xd4, 0x81, 0x3c, 0x75, 0x23, 0x6f, 0x76,
	0xe1, 0x86, 0x49, 0xd2, 0xf2, 0x37, 0x21, 0xc9, 0x4b, 0xb2, 0x6c, 0x4a, 0xe7, 0xc8, 0xb3, 0x3a,
	0xc1, 0x53, 0x6e, 0x45, 0xaa, 0x4a, 0x1b, 0x93, 0xc8, 0xb6, 0x9d, 0xa6, 0x3e, 0xb6, 0x57, 0x84,
	0x5c, 0xfd, 0xe7, 0xe8, 0xb1, 0x1e, 0x43, 0x40, 0xe2, 0x71, 0x40, 0x62, 0x08, 0x1f, 0x06, 0x24,
	0xde, 0x17, 0x89, 0xc4, 0xde, 0x6e, 0xa9, 0x93, 0x7d, 0x0f, 0x70, 0x9d, 0x6b, 0x3e, 0x53, 0xd7,
	0xb9, 0xf1, 0x1f, 0xeb, 0xd0, 0xbd, 0x0a, 0xef, 0x82, 0xe3, 0x7d, 0x3a, 0x97, 0x17, 0x18, 0xca,
	0xc0, 0x5b, 0xdf, 0x16, 0xc9, 0x92, 0x03, 0xa6, 0x8a, 0xd4, 0x21, 0x3d, 0x74, 0x6d, 0x82, 0xe6,
	0x7a, 0x3c, 0x43, 0x36, 0x4b, 0x02, 0x36, 0xec, 0xe1, 0xe7, 0x1f, 0x7f, 0xbe, 0x2c, 0xac, 0xd0,
	0x26, 0xf7, 0xbd, 0x3c, 0xd4, 0x16, 0x11, 0xa3, 0x6d, 0xdf, 0xb0, 0xc9, 0xb0, 0x86, 0x4f, 0xe6,
	0xa8, 0xe6, 0xb8, 0xc2, 0x85, 0x7e, 0x0d, 0xc8, 0x72, 0xf9, 0xe9, 0xd2, 0x8d, 0x29, 0x63, 0x3d,
	0x29, 0x09, 0x9f, 0xff, 0x93, 0x16, 0x41, 0x5e, 0x38, 0x90, 0x75, 0xda, 0xe6, 0x33, 0xbe, 0x01,
	0xfc, 0xa3, 0x7b, 0x0b, 0x3e, 0xd1, 0xf3, 0x80, 0xdc, 0x29, 0x8f, 0xd9, 0x4e, 0x53, 0x3f, 0x9a,
	0x3f, 0xc0, 0x7e, 0xb4, 0x29, 0x21, 0x64, 0x6d, 0x87, 0x16, 0xd1, 0xd6, 0x2c, 0xb4, 0x1d, 0x7e,
	0x31, 0x8c, 0x82, 0xcb, 0x61, 0x14, 0xfc, 0x1e, 0x46, 0xc1, 0xf9, 0x28, 0xaa, 0x5d, 0x8e, 0xa2,
	0xda, 0xcf, 0x51, 0x54, 0x7b, 0xdf, 0x44, 0xfd, 0x69, 0xd1, 0x68, 0xcf, 0x32, 0x69, 0x7a, 0x75,
	0xf7, 0x41, 0xeb, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x70, 0xfa, 0x74, 0x95, 0xb7, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Canvas by index.
	Canvas(ctx context.Context, in *QueryGetCanvasRequest, opts ...grpc.CallOption) (*QueryGetCanvasResponse, error)
	// Queries a StoredColors by index.
	StoredColors(ctx context.Context, in *QueryGetStoredColorsRequest, opts ...grpc.CallOption) (*QueryGetStoredColorsResponse, error)
	// Queries a list of StoredColors items.
	StoredColorsAll(ctx context.Context, in *QueryAllStoredColorsRequest, opts ...grpc.CallOption) (*QueryAllStoredColorsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/canvas.canvas.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Canvas(ctx context.Context, in *QueryGetCanvasRequest, opts ...grpc.CallOption) (*QueryGetCanvasResponse, error) {
	out := new(QueryGetCanvasResponse)
	err := c.cc.Invoke(ctx, "/canvas.canvas.Query/Canvas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredColors(ctx context.Context, in *QueryGetStoredColorsRequest, opts ...grpc.CallOption) (*QueryGetStoredColorsResponse, error) {
	out := new(QueryGetStoredColorsResponse)
	err := c.cc.Invoke(ctx, "/canvas.canvas.Query/StoredColors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredColorsAll(ctx context.Context, in *QueryAllStoredColorsRequest, opts ...grpc.CallOption) (*QueryAllStoredColorsResponse, error) {
	out := new(QueryAllStoredColorsResponse)
	err := c.cc.Invoke(ctx, "/canvas.canvas.Query/StoredColorsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Canvas by index.
	Canvas(context.Context, *QueryGetCanvasRequest) (*QueryGetCanvasResponse, error)
	// Queries a StoredColors by index.
	StoredColors(context.Context, *QueryGetStoredColorsRequest) (*QueryGetStoredColorsResponse, error)
	// Queries a list of StoredColors items.
	StoredColorsAll(context.Context, *QueryAllStoredColorsRequest) (*QueryAllStoredColorsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Canvas(ctx context.Context, req *QueryGetCanvasRequest) (*QueryGetCanvasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Canvas not implemented")
}
func (*UnimplementedQueryServer) StoredColors(ctx context.Context, req *QueryGetStoredColorsRequest) (*QueryGetStoredColorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredColors not implemented")
}
func (*UnimplementedQueryServer) StoredColorsAll(ctx context.Context, req *QueryAllStoredColorsRequest) (*QueryAllStoredColorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredColorsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canvas.canvas.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Canvas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCanvasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Canvas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canvas.canvas.Query/Canvas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Canvas(ctx, req.(*QueryGetCanvasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredColors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredColorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredColors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canvas.canvas.Query/StoredColors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredColors(ctx, req.(*QueryGetStoredColorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredColorsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStoredColorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredColorsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canvas.canvas.Query/StoredColorsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredColorsAll(ctx, req.(*QueryAllStoredColorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "canvas.canvas.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Canvas",
			Handler:    _Query_Canvas_Handler,
		},
		{
			MethodName: "StoredColors",
			Handler:    _Query_StoredColors_Handler,
		},
		{
			MethodName: "StoredColorsAll",
			Handler:    _Query_StoredColorsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "canvas/canvas/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCanvasRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCanvasRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCanvasRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetCanvasResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCanvasResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCanvasResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Canvas.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredColorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredColorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredColorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredColorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredColorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredColorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StoredColors.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredColorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredColorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredColorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredColorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredColorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredColorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StoredColors) > 0 {
		for iNdEx := len(m.StoredColors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StoredColors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCanvasRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetCanvasResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Canvas.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStoredColorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetStoredColorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoredColors.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllStoredColorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStoredColorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StoredColors) > 0 {
		for _, e := range m.StoredColors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCanvasRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCanvasRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCanvasRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCanvasResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCanvasResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCanvasResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Canvas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Canvas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredColorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredColorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredColorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredColorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredColorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredColorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredColors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoredColors.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredColorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredColorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredColorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredColorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredColorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredColorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredColors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredColors = append(m.StoredColors, StoredColors{})
			if err := m.StoredColors[len(m.StoredColors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
